version: '3'
services:
  jenkins:
    container_name: jenkins-container
    build: ./jenkins
    image: devcognitio/jenkins-completo
    ports:
     - "5000:5000"
     - "8080:8080"
    volumes:
     - jenkins-home-compose:/var/jenkins_home
    depends_on:
      - artifactory
      - sonar
  artifactory:
    container_name: artifactory-container
    image: "docker.bintray.io/jfrog/artifactory-cpp-ce"
    ports:
     - "8081:8080"
  sonar:
    container_name: sonar-container
    image: sonarqube
    ports:
     - "9000:9000"

volumes:
  jenkins-home-compose:
  