version: '3'
services:
  jenkins:
    container_name: jenkins-container
    #build: ./jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
     - "5001:5000"
     - "8080:8080"
     - "50000:50000"
    volumes:
     - jenkins-home-compose:/var/jenkins_home

  sonar:
    container_name: sonar-container
    image: sonarqube:lts-community
    #sysctls:
    #  vm.max_map_count: 524288
    #  fs.file-max: 131072
    ports:
      - "9000:9000"
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-logs:/opt/sonarqube/logs
      - sonar-extensions:/opt/sonarqube/extensions
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres/sonarqube
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
    depends_on:
      - postgres

  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_USER: sonarqube
      POSTGRES_DB: sonarqube
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  adminer:
    container_name: adminer-container
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - postgres

  chrome:
    container_name: chrome-container
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900


volumes:
  jenkins-home-compose:
  sonar-data:
  sonar-logs:
  sonar-extensions:
  postgres-data: